neontribe/seap_core

- src/css/style.css
I'm going to sort out the spacing/tabs issue next
> change padding on categories slide for max-width: 500px

- src/css/style.css
> fixed video box styles

- src/css/style.css
- src/index.html
> Header media queries

- src/index.html
> add new paragraph

- src/css/style.css
- src/index.html
A bunch of stuff has moved around to more logical places and changing the privacy/feedback sections to flexbox changed the portal so there are fixes for that too. Boom
> Surveymonkey

- src/css/style.css
> remove underline on ticks ul

- deploy.sh
> live-deploy

- src/js/jquery.waypoints.js
Think i've done this right. It compiles it into the all-scripts.js
> add waypoint js

- src/css/style.css
> Homepagecopy

- src/css/style.css
adds a bit of margin at the bottom now border is gone
> remove border on categories slide

- src/css/style.css
This branch name is too long :deciduous_tree:
> add some margin between #printing-box and #data-box after moving boxes around

- src/css/style.css
Otherwise he doesn't always work! weird (specifically the choose at random a links)
> set a:hover cursor to the little hand guy

- src/css/style.css
- src/privacy.html
> print privacy

- src/index.html
New copy - might want to style differently... like trying Nick's 2 column idea or slightly bigger h4's
Let's see what we all think.
> new copy for C-App home

- src/css/style.css
- src/index.html
It's cold in here today :icecream:
> change button layout and add ticks to buttons

- src/css/style.css
> ul lists on the guide page

- src/css/style.css
> Seap 121 flexbox fallback

- src/css/style.css
> Stop users from being able to highlight text

- src/css/style.css
- src/privacy.html
- Generalises styling from C-App portal to ESA and PIP pages.
- Better support for particularly large/small screen sizes.
> 132 award logo on other sites

- src/index.html
- src/privacy.html
Updated privacy policy
- Address used: http://www.seap.org.uk/privacy-policy.html
- Highlighted text from email used as link text
- Opens in new tab, to match other links
Existing external links on the page don't use rel="noopener"
> 133 update privacy

- src/privacy.html
https://neontribe.atlassian.net/browse/SEAP-148
🦅
> Fix typo in privacy text

- src/css/style.css
- src/index.html
- tests/init_test.js
https://neontribe.atlassian.net/browse/SEAP-149
🔘
> 149 button accessibility

- src/css/style.css
- src/index.html
https://neontribe.atlassian.net/browse/SEAP-146
New button style accessibility:
> 146 donation button

- src/css/style.css
#101 
Fixed the header in privacy page.
> 101-Privacy-page

- .travis.yml
- package.json
The minified files - html, js and css - were not pushed to live because the production build was not generated before the bash deployment phase. This PR fixes that.
> Update Travis config file
